# Generated by Django 3.2.16 on 2024-11-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_value', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grams', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritional_value.ingredient')),
            ],
            options={
                'unique_together': {('date', 'ingredient')},
            },
        ),
    ]
