# Generated by Django 3.2.16 on 2024-11-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_value', '0002_amountperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
