# Generated by Django 3.2.16 on 2024-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_value', '0003_alter_ingredient_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
