# Generated by Django 3.2.16 on 2024-11-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_value', '0006_amountperday_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amountperday',
            unique_together=set(),
        ),
    ]
