# Generated by Django 5.1.3 on 2024-11-19 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_value', '0008_alter_amountperday_grams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountperday',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='amountperday',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='amountperday',
            index=models.Index(fields=['author', 'date'], name='nutritional_author__c9a7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['author', 'slug'], name='nutritional_author__78e0ec_idx'),
        ),
    ]
