# Generated by Django 5.1.3 on 2024-11-21 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_value', '0009_alter_amountperday_options_alter_amountperday_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingredient',
            name='nutritional_author__78e0ec_idx',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['author', 'title'], name='nutritional_author__f91ddc_idx'),
        ),
    ]
